python run_ner.py ^
--pretrained_model_path models/cscd_R_based_on_google_zh_600000_best.bin ^
--vocab_path models/google_zh_vocab.txt ^
--output_model_path ./models/ner_ccks_cscd_mlm.bin ^
--train_path datasets/ccks/train.tsv ^
--dev_path datasets/ccks/dev.tsv ^
--test_path datasets/ccks/test.tsv ^
--embedding bert ^
--encoder bert ^
--learning_rate 2e-5 ^
--warmup 0.1 ^
--epochs_num 8 ^
--seq_length 128 ^
--batch_size 16 ^
--report_steps 50 ^
--gpu_rank 0
